- id: menu-items-standard.front_page
  drupal_id: null
  alias: ''
  url: /
  title: Home
  parent: null
  children: []
- id: 'menu-items-menu_link_content:0e271628-af49-452a-b4b8-57321caec4f6'
  drupal_id: '45'
  alias: ''
  url: /careers
  title: Careers
  parent: null
  children: []
- id: 'menu-items-menu_link_content:36a14f1d-8c92-4524-ac43-b4444d2ff7b7'
  drupal_id: '44'
  alias: ''
  url: /recruitment
  title: Recruitment
  parent: null
  children:
    - id: 'menu-items-menu_link_content:6d2ecc3d-5586-4863-a6aa-9222fd24c320'
      drupal_id: '46'
      alias: ''
      url: /sub-page-recruitment
      title: Sub-page of Recruitment
      parent:
        id: 'menu-items-menu_link_content:36a14f1d-8c92-4524-ac43-b4444d2ff7b7'
      children: []
- id: 'menu-items-menu_link_content:ae2b8c75-1369-4e3f-85a3-d9f2f41d7457'
  drupal_id: '38'
  alias: ''
  url: /soil-health
  title: Soil Health
  parent: null
  children: []
- id: 'menu-items-menu_link_content:e87140ba-5247-448c-add2-48257117e4da'
  drupal_id: null
  alias: ''
  url: 'https://indigenous.uoguelph.ca'
  title: External URL
  parent: null
  children: []
