- id: 'menu-items-menu_link_content:f919b8ed-f514-47ae-b19d-3594f6bd6ff8'
  drupal_id: '20'
  alias: /soil-health
  url: /soil-health
  title: Soil Health
  parent: null
  children: []
- id: 'menu-items-menu_link_content:24e5808f-4922-46ae-a318-3aa3d587d267'
  drupal_id: '26'
  alias: /one-health
  url: /one-health
  title: One Health
  parent: null
  children: []
- id: 'menu-items-menu_link_content:e5374eb1-709b-49b7-84ab-1b3b6b75e05e'
  drupal_id: '27'
  alias: /recruitment
  url: /recruitment
  title: Recruitment
  parent: null
  children:
    - id: 'menu-items-menu_link_content:0e0f22f7-01a3-497b-9b0f-59586c7e4f97'
      drupal_id: '22'
      alias: /study-food
      url: /study-food
      title: Study Food
      parent:
        id: 'menu-items-menu_link_content:e5374eb1-709b-49b7-84ab-1b3b6b75e05e'
      children: []
    - id: 'menu-items-menu_link_content:fbd22881-fe4a-4b66-8615-394eadad6446'
      drupal_id: '23'
      alias: /study-the-environment
      url: /study-environment
      title: Study the Environment
      parent:
        id: 'menu-items-menu_link_content:e5374eb1-709b-49b7-84ab-1b3b6b75e05e'
      children: []
    - id: 'menu-items-menu_link_content:652f9ddc-27b8-49dc-b552-796d741f01f5'
      drupal_id: '25'
      alias: /study-animals
      url: /study-animals
      title: Study Animals
      parent:
        id: 'menu-items-menu_link_content:e5374eb1-709b-49b7-84ab-1b3b6b75e05e'
      children: []
    - id: 'menu-items-menu_link_content:96513521-b809-4d36-9310-2742f22cc1f2'
      drupal_id: '24'
      alias: /study-stem
      url: /study-stem
      title: Study STEM
      parent:
        id: 'menu-items-menu_link_content:e5374eb1-709b-49b7-84ab-1b3b6b75e05e'
      children: []
