- id: 'menu-items-menu_link_content:ab27146f-e01e-4cbd-9de2-8101021d992e'
  drupal_id: '20'
  alias: /soil-health
  url: /soil-health
  title: Soil Health
  parent: null
  children: []
- id: 'menu-items-menu_link_content:db345dee-4a03-42b9-999a-5f72527e1555'
  drupal_id: '26'
  alias: /one-health
  url: /one-health
  title: One Health
  parent: null
  children: []
- id: 'menu-items-menu_link_content:f90e3319-35e6-42ca-be92-9817dc9d0d3b'
  drupal_id: '27'
  alias: /recruitment
  url: /recruitment
  title: Recruitment
  parent: null
  children:
    - id: 'menu-items-menu_link_content:228d344a-9446-409d-a171-f08edff75ec3'
      drupal_id: '22'
      alias: /study-food
      url: /study-food
      title: Study Food
      parent:
        id: 'menu-items-menu_link_content:f90e3319-35e6-42ca-be92-9817dc9d0d3b'
      children: []
    - id: 'menu-items-menu_link_content:de8671f5-955c-46c7-96ca-ba6c5d7ea956'
      drupal_id: '23'
      alias: /study-the-environment
      url: /study-environment
      title: Study the Environment
      parent:
        id: 'menu-items-menu_link_content:f90e3319-35e6-42ca-be92-9817dc9d0d3b'
      children: []
    - id: 'menu-items-menu_link_content:1514c856-cd58-468d-aa63-6646de8815c4'
      drupal_id: '25'
      alias: /study-animals
      url: /study-animals
      title: Study Animals
      parent:
        id: 'menu-items-menu_link_content:f90e3319-35e6-42ca-be92-9817dc9d0d3b'
      children: []
    - id: 'menu-items-menu_link_content:24a79fc8-1820-4d03-bb3c-de0b7dff7d2f'
      drupal_id: '24'
      alias: /study-stem
      url: /study-stem
      title: Study STEM
      parent:
        id: 'menu-items-menu_link_content:f90e3319-35e6-42ca-be92-9817dc9d0d3b'
      children: []
