- id: 'menu-items-menu_link_content:27b7a5fe-72ad-4893-ad44-eabc03b434a5'
  drupal_id: null
  alias: ''
  url: 'https://twitter.com/uofg'
  title: Twitter
  parent: null
  children: []
- id: 'menu-items-menu_link_content:9b072561-5ef1-41f1-92d5-e21bd1099fcf'
  drupal_id: null
  alias: ''
  url: 'https://www.facebook.com/uofguelph'
  title: Facebook
  parent: null
  children: []
- id: 'menu-items-menu_link_content:e40d420e-9c20-4fa6-9adb-a7701dc63a6a'
  drupal_id: null
  alias: ''
  url: 'https://instagram.com/uofguelph/'
  title: Instagram
  parent: null
  children: []
- id: 'menu-items-menu_link_content:878f4b6a-d103-45fe-9a16-06f259127700'
  drupal_id: null
  alias: ''
  url: 'https://www.youtube.com/uofguelph'
  title: YouTube
  parent: null
  children: []
- id: 'menu-items-menu_link_content:3bfd34d3-d87f-4beb-968a-82bd7c9e023c'
  drupal_id: null
  alias: ''
  url: 'https://www.linkedin.com/company/university-of-guelph'
  title: LinkedIn
  parent: null
  children: []
- id: 'menu-items-menu_link_content:00f5b7ee-5c23-4e94-8ff0-7391838529c1'
  drupal_id: null
  alias: ''
  url: 'https://www.uoguelph.ca/web/socialmedia/'
  title: Social Media Directory
  parent: null
  children: []
