- id: 'menu-items-menu_link_content:33af1efb-2eb3-404b-9564-dbb5ec7d9ca7'
  drupal_id: null
  alias: ''
  url: 'https://twitter.com/uofg'
  title: Twitter
  description: null
  parent: null
  children: []
- id: 'menu-items-menu_link_content:a14dfdbd-36df-4e17-a3a4-e49157774818'
  drupal_id: null
  alias: ''
  url: 'https://www.facebook.com/uofguelph'
  title: Facebook
  description: null
  parent: null
  children: []
- id: 'menu-items-menu_link_content:66f66970-8b35-4a46-a032-80a5d3a3488e'
  drupal_id: null
  alias: ''
  url: 'https://instagram.com/uofguelph/'
  title: Instagram
  description: null
  parent: null
  children: []
- id: 'menu-items-menu_link_content:cac8a22c-f8e5-4198-930f-d48fb2a4bb07'
  drupal_id: null
  alias: ''
  url: 'https://www.youtube.com/uofguelph'
  title: YouTube
  description: null
  parent: null
  children: []
- id: 'menu-items-menu_link_content:dcf8a5ae-cfff-4804-9c03-61539310de2d'
  drupal_id: null
  alias: ''
  url: 'https://www.linkedin.com/company/university-of-guelph'
  title: LinkedIn
  description: null
  parent: null
  children: []
- id: 'menu-items-menu_link_content:88c68324-5a5b-4f80-935e-62de8859207d'
  drupal_id: null
  alias: ''
  url: 'http://www.uoguelph.ca/web/socialmedia/'
  title: Social Media Directory
  description: null
  parent: null
  children: []
