# This is a basic workflow to help you get started with Actions

name: CI for Gatsby Cloud

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Call webhook
        run: curl -X POST https://webhook.gatsbyjs.com/hooks/data_source/publish/fc8e90a4-54ce-4012-a5fc-3302f05a3d6d

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
